---
version: '3'

services:
  drupal:
    image: geerlingguy/drupal-for-kubernetes:latest
    container_name: drupal-for-kubernetes
    environment:
      DRUPAL_DB_HOST: mysql
      DRUPAL_DB_PASSWORD: drupal
      DRUPAL_DOWNLOAD_IF_NOT_PRESENT: "false"
    ports:
      - "80:80"
    restart: always
    # Share the project into the container for local development. Comment out
    # this line to test the production-ready pre-built container codebase.
    volumes: ['./:/var/www/html:rw,delegated']

  mysql:
    image: mysql:5.7
    container_name: drupal-mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
